package internal

import (
	"testing"

	r "github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

// OpenShift MachineConfig expected outputs grouped by embedded ignition version.
// OpenShift variants output YAML MachineConfig rather than plain ignition JSON.

const openshiftIgnV32Expected = `# Generated by Butane; do not edit
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker
spec:
  config:
    ignition:
      version: 3.2.0
    passwd:
      users:
        - name: core
          sshAuthorizedKeys:
            - key`

const openshiftIgnV34Expected = `# Generated by Butane; do not edit
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker
spec:
  config:
    ignition:
      version: 3.4.0
    passwd:
      users:
        - name: core
          sshAuthorizedKeys:
            - key`

const openshiftIgnV35Expected = `# Generated by Butane; do not edit
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker
spec:
  config:
    ignition:
      version: 3.5.0
    passwd:
      users:
        - name: core
          sshAuthorizedKeys:
            - key`

// Openshift variant, v4.8.0 - v4.13.0 (ignition v3.2)

func openshiftResource(version string) string {
	return `
data "ct_config" "openshift" {
  pretty_print = true
  use_mapped_version = true
  strict = true
  content = <<EOT
---
variant: openshift
version: ` + version + `
metadata:
  name: worker
  labels:
    machineconfiguration.openshift.io/role: worker
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - key
EOT
}
`
}

func TestButaneConfig_Openshift_v4_8(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.8.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV32Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_9(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.9.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV32Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_10(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.10.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV32Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_11(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.11.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV32Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_12(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.12.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV32Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_13(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.13.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV32Expected),
				),
			},
		},
	})
}

// Openshift variant, v4.14.0 - v4.18.0 (ignition v3.4)

func TestButaneConfig_Openshift_v4_14(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.14.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV34Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_15(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.15.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV34Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_16(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.16.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV34Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_17(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.17.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV34Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_18(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.18.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV34Expected),
				),
			},
		},
	})
}

// Openshift variant, v4.19.0 - v4.21.0 (ignition v3.5)

func TestButaneConfig_Openshift_v4_19(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.19.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV35Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_20(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.20.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV35Expected),
				),
			},
		},
	})
}

func TestButaneConfig_Openshift_v4_21(t *testing.T) {
	r.UnitTest(t, r.TestCase{
		Providers: testProviders,
		Steps: []r.TestStep{
			{
				Config: openshiftResource("4.21.0"),
				Check: r.ComposeTestCheckFunc(
					r.TestCheckResourceAttr("data.ct_config.openshift", "rendered", openshiftIgnV35Expected),
				),
			},
		},
	})
}
